- hosts: sandbox.odp.org
  user: vagrant
  sudo: True
  gather_facts: False
  roles:
    - common

- hosts: sandbox.odp.org
  user: root
  gather_facts: False
  roles:
    - clusternode
    - namenode
    - datanode
    - { role: hive_latest, odp_version: '0.9.0.1-56', tags: ['hive'] }
    - itester
    - sandbox
